version: "3"

services:
  db:
    image: "postgres:14"
    container_name: "pg"
    ports:
      - "5434:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    env_file:
      - ./pt-dc.env
    networks:
      - main

  api:
    image: "papertrade:latest"
    build: .
    container_name: "pt"
    ports:
      - "9000:9000"
    env_file:
      - ./pt-dc.env
    networks:
      - main
    depends_on:
      - db
    command: ["./start"]
    restart: on-failure

volumes:
  dbdata:

networks:
  main:
