"""models_fix

Revision ID: 1db58cfc418b
Revises: 009f7e99be0e
Create Date: 2023-07-13 18:49:33.666552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1db58cfc418b"
down_revision = "009f7e99be0e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
