"""portfolio_stock updated

Revision ID: 4a905f7fb497
Revises: 5699754294cd
Create Date: 2023-08-07 12:26:03.714582

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4a905f7fb497"
down_revision = "5699754294cd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "portfolio_stock", sa.Column("asset_name", sa.String(length=50), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("portfolio_stock", "asset_name")
    # ### end Alembic commands ###
