"""transaction_model_fix

Revision ID: 5699754294cd
Revises: cc822c6b9dc9
Create Date: 2023-07-31 18:18:39.349761

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5699754294cd"
down_revision = "cc822c6b9dc9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "transaction_portfolio_stock_id_fkey", "transaction", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "transaction",
        "portfolio_stock",
        ["portfolio_stock_id"],
        ["portfolio_stock_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transaction", type_="foreignkey")
    op.create_foreign_key(
        "transaction_portfolio_stock_id_fkey",
        "transaction",
        "portfolio",
        ["portfolio_stock_id"],
        ["portfolio_id"],
    )
    # ### end Alembic commands ###
