"""bugfix

Revision ID: cc822c6b9dc9
Revises: f585e9a8a4d7
Create Date: 2023-07-30 12:37:00.790973

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "cc822c6b9dc9"
down_revision = "f585e9a8a4d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
